name: authenticate-commits
env:
  TRUST_ROOT: ae2291afdaee0e648eb1010d275d4ab0e8e4e58c
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  authenticate-commits:
    runs-on: fedora-latest

    permissions:
      contents: read
      pull-requests: write
      issues: write

    steps:
      - name: Install sq-git
        run: dnf install -y sequoia-git
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Authenticating commits
        run: sq-git log --trust-root $TRUST_ROOT
