[package]
name = "xtask"
license = "GPL-3.0-or-later"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.94"
indoc = "2.0.5"
jiff = { version = "0.2.0", default-features = false, features = ["std"] }
xflags = "0.3.2"
xshell = "0.2.7"
