[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
indoc = "2.0.5"
jiff = { version = "0.2.0", default-features = false, features = ["std"] }
xflags = "0.3.2"
