// SPDX-License-Identifier: GPL-3.0-or-later

import { GridBox, Button, VerticalBox, HorizontalBox } from "std-widgets.slint";

export component BopomofoKeyboard inherits VerticalBox {

    callback clicked(text: string);
    // callback backspace-clicked();
    callback clear-clicked();
    callback done();

    property <[[string]]> keys: [
        [
            "ㄅ",
            "ㄉ",
            "ˇ",
            "ˋ",
            "ㄓ",
            "ˊ",
            "˙",
            "ㄚ",
            "ㄞ",
            "ㄢ",
            "ㄦ",
        ],
        ["ㄆ", "ㄊ", "ㄍ", "ㄐ", "ㄔ", "ㄗ", "ㄧ", "ㄛ", "ㄟ", "ㄣ"],
        ["ㄇ", "ㄋ", "ㄎ", "ㄑ", "ㄕ", "ㄘ", "ㄨ", "ㄜ", "ㄠ", "ㄤ"],
        ["ㄈ", "ㄌ", "ㄏ", "ㄒ", "ㄖ", "ㄙ", "ㄩ", "ㄝ", "ㄡ", "ㄥ"]
    ];

    for row[index] in root.keys: HorizontalLayout {
        padding-left: 10px * index;
        for btn in row: Rectangle {
            width: 40px;
            height: 30px;
            if btn == "": Rectangle { }
            if btn != "": Button {
                text: btn;
                clicked => {
                    root.clicked(self.text)
                }
            }
        }
        // if index == 1: Rectangle {
        //     width: 50px;
        //     height: 30px;
        //     Button {
        //         text: "⌫";
        //         clicked => {
        //             backspace-clicked()
        //         }
        //     }
        // }
    }
    HorizontalLayout {
        Rectangle {
            width: 40px;
        }

        Rectangle {
            width: 70px;
            height: 30px;
            Button {
                text: "清空";
                clicked => {
                    clear-clicked()
                }
            }
        }

        Rectangle {
            width: 240px;
            height: 30px;
            Button {
                width: 100%;
                text: "␣";
                clicked => {
                    root.clicked(self.text)
                }
            }
        }

        Rectangle {
            width: 80px;
            height: 30px;
            Button {
                primary: true;
                text: "確定";
                clicked => {
                    root.done();
                }
            }
        }
    }
}
