// SPDX-License-Identifier: GPL-3.0-or-later

import { Button, VerticalBox, HorizontalBox } from "std-widgets.slint";
import { AboutChewing } from "about-box.slint";
import { Assets, Version } from "globals.slint";

export component AboutWindow inherits Window {
    title: "關於新酷音輸入法 (" + Version.product-version + ")";
    icon: Assets.icon;
    preferred-width: 350px;
    preferred-height: 300px;
    max-width: 350px;
    max-height: 300px;

    callback done();

    VerticalBox {
        alignment: start;
        AboutChewing { }

        HorizontalBox {
            alignment: end;
            Button {
                text: "確定";
                clicked => {
                    done();
                }
            }
        }
    }
}
