import { Button, VerticalBox, TabWidget, CheckBox, ComboBox, HorizontalBox, SpinBox, AboutSlint, TextEdit, StandardButton } from "std-widgets.slint";

export component AppWindow inherits Window {
    default-font-family: "jf open 粉圓 2.0";
    default-font-weight: 500;
    title: "Chewing Preferences (24.10.1.999)";
    icon: @image-url("../../icon/48_icon.png");
    max-width: 500px;
    max-height: 500px;
    VerticalBox {

        TabWidget {
            Tab {
                title: "打字行為";
                HorizontalLayout {
                    padding: 20px;
                    spacing: 20px;
                    VerticalLayout {
                        spacing: 10px;
                        alignment: start;
                        CheckBox {
                            text: "使用 Shift 快速切換中英文";
                        }

                        CheckBox {
                            text: "使用 CapsLock 切換中英文";
                        }

                        CheckBox {
                            text: "使用 Esc 清空編輯區字串";
                        }

                        CheckBox {
                            text: "按住 Shift 輸入全形標點符號";
                        }

                        CheckBox {
                            text: "按住 Shift 輸入大寫英文字母";
                        }

                        CheckBox {
                            text: "Ctrl + 數字儲存游標前方的詞";
                        }

                        CheckBox {
                            text: "按住 Shift 輸入快速符號";
                            checked: true;
                            enabled: false;
                        }

                        CheckBox {
                            text: "按住 Ctrl 輸入快速符號";
                            enabled: false;
                        }
                    }

                    VerticalLayout {
                        spacing: 10px;
                        alignment: start;
                        CheckBox {
                            text: "使用方向鍵移動游標選字";
                        }

                        CheckBox {
                            text: "按空白鍵叫出選字視窗";
                        }

                        CheckBox {
                            text: "選字完畢自動跳到下一個字";
                        }

                        CheckBox {
                            text: "預設以全形模式啟動";
                        }

                        CheckBox {
                            text: "預設以英文模式啟動";
                        }

                        CheckBox {
                            text: "預設輸出簡體中文";
                        }

                        Text {
                            text: "選字鍵：";
                        }

                        ComboBox {
                            model: ["1234567890"];
                        }

                        Text {
                            text: "模式：";
                        }

                        ComboBox { }
                    }
                }
            }

            Tab {
                title: "界面外觀";
                VerticalBox {
                    alignment: start;
                    Text {
                        text: "每列顯示後選字個數";
                        min-width: 140px;
                    }

                    SpinBox {
                        minimum: 1;
                        maximum: 10;
                    }

                    Text {
                        text: "每頁顯示後選字個數";
                        min-width: 140px;
                    }

                    SpinBox {
                        minimum: 1;
                        maximum: 10;
                    }

                    Text {
                        text: "選字及訊息視窗文字大小";
                        min-width: 140px;
                    }

                    SpinBox {
                        minimum: 10;
                    }
                }
            }

            Tab {
                title: "鍵盤設定";
            }

            Tab {
                title: "特殊符號";
                VerticalBox {
                    Text {
                        text: "輸入中文時，按下 ` 鍵，會顯示下列的符號表：";
                    }

                    TextEdit { }

                    Text {
                        text: "以上是符號表的設定檔，語法相當簡單：\n每一行的內容都是：「分類名稱」＝「此分類下的所有符號」\n您也可以一行只放一個符號，則該符號會被放在最上層選單。";
                    }
                }
            }

            Tab {
                title: "關於";
                AboutSlint { }
            }
        }

        HorizontalBox {
            alignment: end;
            StandardButton {
                kind: apply;
            }

            StandardButton {
                kind: cancel;
            }
        }
    }
}
