import { VerticalBox, StandardTableView, Button, TabWidget, HorizontalBox, LineEdit, AboutSlint, StandardButton, GridBox } from "std-widgets.slint";

export struct DictionaryListItem {
    id: int,
    type: string,
    name: string,
}

export component EditorWindow inherits Window {
    default-font-family: "jf open 粉圓 2.0";
    default-font-weight: 500;
    preferred-height: 500px;
    
    in property <[[StandardListViewItem]]> dictionaries;
    in property <[[StandardListViewItem]]> entries;
    out property <int> current-row: table.current-row;

    callback info-clicked(row: [StandardListViewItem]);
    callback edit-dict-clicked(row: [StandardListViewItem]);
    callback edit-entry-clicked(phrase: string, bopomofo: string, freq: int);

    tabs := TabWidget {
        Tab {
            title: "管理";
            VerticalBox {
                HorizontalBox {
                    alignment: start;
                    Button {
                        text: "編輯";
                        enabled: root.current-row >= 0;
                        clicked => {
                            root.edit-dict-clicked(root.dictionaries[root.current-row]);
                            tabs.current-index = 1;
                        }
                    }
                    Button {
                        text: "內容";
                        enabled: root.current-row >= 0;
                        clicked => {
                            root.info-clicked(root.dictionaries[root.current-row]);
                        }
                    }
                    Button {
                        text: "新增";
                    }
                    Button {
                        text: "匯入";
                    }
                    Button {
                        text: "匯出";
                    }
                    Button {
                        text: "刪除";
                    }
                    Button {
                        text: "重新整理";
                    }
                }
                table := StandardTableView {
                    columns: [
                        { title: "類型", width: 70px },
                        {
                            title: "名稱"
                        }
                    ];
                    rows: root.dictionaries;
                }
            }
        }
        Tab {
            title: "編輯";
            VerticalBox {
                HorizontalBox {
                    alignment: start;
                    Button {
                        text: "新增";
                        enabled: false;
                    }
                    Button {
                        text: "刪除";
                        enabled: false;
                    }
                    Button {
                        text: "復原";
                        enabled: false;
                    }
                    Button {
                        text: "放棄";
                        enabled: false;
                    }
                    Button {
                        text: "重新整理";
                        enabled: false;
                    }
                    Button {
                        text: "存檔";
                        enabled: false;
                    }
                }
                HorizontalBox {
                    LineEdit {
                        text: "搜尋";
                        enabled: false;
                    }
                }
                StandardTableView {
                    columns: [{ title: "字/詞" }, { title: "注音" }, { title: "詞頻" }];
                    rows: entries;
                    current-row-changed(current-row) => {
                        root.edit-entry-clicked(
                            root.entries[current-row][0].text,
                            root.entries[current-row][1].text,
                            root.entries[current-row][2].text.to-float()
                        )
                    }
                }
            }
        }
        Tab {
            title: "關於";
            AboutSlint {}
        }
    }
}

export component DictionaryInfoDialog inherits Dialog {
    default-font-family: "jf open 粉圓 2.0";
    default-font-weight: 500;
    preferred-height: 400px;

    in property <[[StandardListViewItem]]> dictionary-info;

    callback ok-clicked();

    VerticalBox {
        StandardTableView {
            columns: [ { title: "屬性", width: 100px }, { title: "內容" } ];
            rows: root.dictionary-info;
        }
    }
    StandardButton {
        kind: ok;
        clicked => {
            root.ok-clicked();
        }
    }
}

export component EditEntryDialog inherits Dialog {
    default-font-family: "jf open 粉圓 2.0";
    default-font-weight: 500;
    preferred-height: 400px;

    in-out property <string> phrase;
    in-out property <string> bopomofo;
    in-out property <int> freq;

    VerticalBox {
        alignment: start;
        Text {
            text: "字/詞：";
        }
        LineEdit {
            text: root.phrase;
        }
        Text {
            text: "注音：";
        }
        LineEdit {
            text: root.bopomofo;
        }
        Text {
            text: "詞頻：";
        }
        LineEdit {
            text: root.freq;
        }
        GridBox {
            spacing: 5px;
            Row {
                Button { text: "ㄅ"; }
                Button { text: "ㄉ"; }
                Button { text: "ˇ"; }
                Button { text: "ˋ"; }
                Button { text: "ㄓ"; }
                Button { text: "ˊ"; }
                Button { text: "˙"; }
                Button { text: "ㄚ"; }
                Button { text: "ㄞ"; }
                Button { text: "ㄢ"; }
                Button { text: "ㄦ"; }
            }
            Row {
                Button { text: "ㄆ"; }
                Button { text: "ㄊ"; }
                Button { text: "ㄍ"; }
                Button { text: "ㄐ"; }
                Button { text: "ㄔ"; }
                Button { text: "ㄗ"; }
                Button { text: "一"; }
                Button { text: "ㄛ"; }
                Button { text: "ㄟ"; }
                Button { text: "ㄣ"; }
            }
            Row {
                Button { text: "ㄇ"; }
                Button { text: "ㄋ"; }
                Button { text: "ㄎ"; }
                Button { text: "ㄑ"; }
                Button { text: "ㄕ"; }
                Button { text: "ㄘ"; }
                Button { text: "ㄨ"; }
                Button { text: "ㄜ"; }
                Button { text: "ㄠ"; }
                Button { text: "ㄤ"; }
            }
            Row {
                Button { text: "ㄈ"; }
                Button { text: "ㄌ"; }
                Button { text: "ㄏ"; }
                Button { text: "ㄒ"; }
                Button { text: "ㄖ"; }
                Button { text: "ㄙ"; }
                Button { text: "ㄩ"; }
                Button { text: "ㄝ"; }
                Button { text: "ㄡ"; }
                Button { text: "ㄥ"; }
            }
            Row {
                Button { text: " "; col: 2; colspan: 6; }
            }
        }
    }
    StandardButton {
        kind: ok;
    }
}