[package]
name = "tsfreg"
version = "24.10.314"
edition = "2021"

[dependencies]
windows = { version = "0.58.0", features = [
    "Win32_Globalization",
    "Win32_System_Com",
    "Win32_UI_TextServices",
    "Win32_UI_Input_KeyboardAndMouse",
] }
