[package]
name = "tsfreg"
version = "24.10.1"
edition = "2024"

[dependencies]
windows = { version = "0.61.0", features = [
    "Win32_Globalization",
    "Win32_System_Com",
    "Win32_UI_TextServices",
    "Win32_UI_Input_KeyboardAndMouse",
] }
