[package]
name = "tsfreg"
version = "0.1.0"
edition = "2021"

[dependencies]
windows = { version = "0.57.0", features = [
    "Win32_Globalization",
    "Win32_System_Com",
    "Win32_UI_TextServices",
] }
